import { User, PurchaseItem, WarrantyRequest, WarrantyCertificate, ProductTemplate } from './types';

export const INITIAL_CUSTOMER: User = {
  id: 'usr_rahul_sharma',
  name: 'Rahul Sharma',
  email: 'rahul@gmail.com',
  phone: '9876543210',
  role: 'CUSTOMER',
  age: 28,
  aadharNumber: 'XXXX XXXX 5678',
  address: 'No. 28, Magadi Main Road, Bangalore, Karnataka 560079',
  totalPurchases: 2,
  totalSpent: 78500,
  memberSince: '10 Jan 2024',
};

export const INITIAL_ADMIN: User = {
  id: 'usr_admin_01',
  name: 'Orange Solar Administrator',
  email: 'admin@orangesolar.co.in',
  phone: '9740097000',
  role: 'ADMIN',
};

export const INITIAL_PURCHASES: PurchaseItem[] = [
  {
    id: 'pur_1',
    product: 'Diamond Glass Line Ultimate',
    model: 'ETC 200 LPD Ultimate',
    serialNumber: 'OS-DGLU-88219',
    date: '20 May 2024',
    price: 34500,
    discount: 1500,
    amount: 33000,
    storeName: 'Orange Solar Authorised Depot Bangalore',
    hasWarranty: true,
  },
  {
    id: 'pur_2',
    product: 'Pressurised FPC Solar Water Heater',
    model: 'FPC 300 LPD Pressurised',
    serialNumber: 'OS-PFPC-44102',
    date: '15 Mar 2024',
    price: 45500,
    discount: 2000,
    amount: 43500,
    storeName: 'Sun Zone Solar System India Pvt Ltd',
    hasWarranty: true,
  },
];

export const INITIAL_REQUESTS: WarrantyRequest[] = [
  {
    id: 'req_1',
    requestId: 'REQ12345',
    customerName: 'Rahul Sharma',
    customerPhone: '9876543210',
    customerEmail: 'rahul@gmail.com',
    productName: 'Diamond Glass Line Ultimate',
    productModel: 'ETC 200 LPD Ultimate',
    serialNumber: 'OS-DGLU-88219',
    purchaseDate: '20 May 2024',
    storeName: 'Orange Solar Authorised Depot Bangalore',
    price: 34500,
    status: 'Approved',
    submissionDate: '20 May 2024',
    reviewedDate: '20 May 2024',
    certificateNo: 'EW-2024-8841',
    notificationSent: { email: true, whatsapp: true },
    imageUrl: 'https://orangesolar.co.in/wp-content/uploads/2021/04/diamond-glass-line-ultimate.jpg',
  },
  {
    id: 'req_2',
    requestId: 'REQ12346',
    customerName: 'Priya Patel',
    customerPhone: '9811223344',
    customerEmail: 'priya.patel@example.com',
    productName: 'Prime Ceramic Solar Water Heater',
    productModel: 'ETC 250 LPD Prime Ceramic',
    serialNumber: 'OS-PRIME-90214',
    purchaseDate: '21 May 2024',
    storeName: 'Orange Solar Direct Store Mysore Road',
    price: 38900,
    status: 'Pending',
    submissionDate: '21 May 2024',
    imageUrl: 'https://orangesolar.co.in/wp-content/uploads/2021/04/prime-ceramic.jpg',
  },
  {
    id: 'req_3',
    requestId: 'REQ12347',
    customerName: 'Amit Kumar',
    customerPhone: '9844556677',
    customerEmail: 'amit.kumar@example.com',
    productName: 'Domestic Heat Pump Water Heater',
    productModel: 'HP 200 LPD All-in-One',
    serialNumber: 'OS-DHP-11029',
    purchaseDate: '22 May 2024',
    storeName: 'Sun Zone Solar System India Pvt Ltd',
    price: 68000,
    status: 'Approved',
    submissionDate: '22 May 2024',
    reviewedDate: '22 May 2024',
    certificateNo: 'EW-2024-8842',
    notificationSent: { email: true, whatsapp: true },
    imageUrl: 'https://orangesolar.co.in/wp-content/uploads/2021/04/domestic-heat-pump.jpg',
  },
  {
    id: 'req_4',
    requestId: 'REQ12344',
    customerName: 'Neha Singh',
    customerPhone: '9877889900',
    customerEmail: 'neha.singh@example.com',
    productName: 'Eco Deluxe Solar Water Heater',
    productModel: 'ETC 150 LPD Eco Deluxe',
    serialNumber: 'OS-ECO-33918',
    purchaseDate: '23 May 2024',
    storeName: 'Third Party Reseller',
    price: 24500,
    status: 'Rejected',
    submissionDate: '23 May 2024',
    reviewedDate: '24 May 2024',
    rejectionReason: 'Invoice serial number does not match factory dispatch ledger.',
    imageUrl: 'https://orangesolar.co.in/wp-content/uploads/2021/04/eco-deluxe.jpg',
  },
  {
    id: 'req_5',
    requestId: 'REQ12348',
    customerName: 'Rahul Sharma',
    customerPhone: '9876543210',
    customerEmail: 'rahul@gmail.com',
    productName: 'Pressurised FPC Solar Water Heater',
    productModel: 'FPC 300 LPD Pressurised',
    serialNumber: 'OS-PFPC-44102',
    purchaseDate: '20 May 2024',
    storeName: 'Sun Zone Solar System India Pvt Ltd',
    price: 45500,
    status: 'Pending',
    submissionDate: '24 May 2024',
    imageUrl: 'https://orangesolar.co.in/wp-content/uploads/2021/04/pressurised-solar-water-heater.jpg',
  },
];

export const INITIAL_CERTIFICATES: WarrantyCertificate[] = [
  {
    certificateNo: 'EW-2024-8841',
    requestId: 'REQ12345',
    customerName: 'Rahul Sharma',
    customerPhone: '9876543210',
    customerEmail: 'rahul@gmail.com',
    productName: 'Diamond Glass Line Ultimate (ETC 200 LPD)',
    productModel: 'ETC 200 LPD Ultimate',
    serialNumber: 'OS-DGLU-88219',
    purchaseDate: '20 May 2024',
    warrantyPeriod: '7 Years',
    validFrom: '20 May 2024',
    validTill: '19 May 2031',
    storeName: 'Orange Solar Authorised Depot Bangalore',
    price: 34500,
    issuedAt: '20 May 2024',
    verificationUrl: '/verify/EW-2024-8841',
    emailSent: true,
    whatsappSent: true,
    imageUrl: 'https://orangesolar.co.in/wp-content/uploads/2021/04/diamond-glass-line-ultimate.jpg',
  },
  {
    certificateNo: 'EW-2024-8842',
    requestId: 'REQ12347',
    customerName: 'Amit Kumar',
    customerPhone: '9844556677',
    customerEmail: 'amit.kumar@example.com',
    productName: 'Domestic Heat Pump Water Heater (HP 200 LPD)',
    productModel: 'HP 200 LPD All-in-One',
    serialNumber: 'OS-DHP-11029',
    purchaseDate: '22 May 2024',
    warrantyPeriod: '5 Years',
    validFrom: '22 May 2024',
    validTill: '21 May 2029',
    storeName: 'Sun Zone Solar System India Pvt Ltd',
    price: 68000,
    issuedAt: '22 May 2024',
    verificationUrl: '/verify/EW-2024-8842',
    emailSent: true,
    whatsappSent: true,
    imageUrl: 'https://orangesolar.co.in/wp-content/uploads/2021/04/domestic-heat-pump.jpg',
  },
];

export const DEMO_PRODUCTS = [
  {
    name: 'Diamond Glass Line Ultimate',
    model: 'ETC 200 LPD Ultimate',
    serialNumber: 'OS-DGLU-' + Math.floor(10000 + Math.random() * 90000),
    storeName: 'Orange Solar Authorised Depot Bangalore',
    price: 34500,
    warrantyPeriod: '7 Years',
    imageUrl: 'https://orangesolar.co.in/wp-content/uploads/2021/04/diamond-glass-line-ultimate.jpg',
  },
  {
    name: 'Prime Ceramic Solar Water Heater',
    model: 'ETC 250 LPD Prime Ceramic',
    serialNumber: 'OS-PRIME-' + Math.floor(10000 + Math.random() * 90000),
    storeName: 'Orange Solar Direct Store Mysore Road',
    price: 38900,
    warrantyPeriod: '5 Years',
    imageUrl: 'https://orangesolar.co.in/wp-content/uploads/2021/04/prime-ceramic.jpg',
  },
  {
    name: 'Pressurised FPC Solar Water Heater',
    model: 'FPC 300 LPD Pressurised',
    serialNumber: 'OS-PFPC-' + Math.floor(10000 + Math.random() * 90000),
    storeName: 'Sun Zone Solar System India Pvt Ltd',
    price: 45500,
    warrantyPeriod: '5 Years',
    imageUrl: 'https://orangesolar.co.in/wp-content/uploads/2021/04/pressurised-solar-water-heater.jpg',
  },
  {
    name: 'Domestic Heat Pump Water Heater',
    model: 'HP 200 LPD All-in-One',
    serialNumber: 'OS-DHP-' + Math.floor(10000 + Math.random() * 90000),
    storeName: 'Sun Zone Solar System India Pvt Ltd',
    price: 68000,
    warrantyPeriod: '5 Years',
    imageUrl: 'https://orangesolar.co.in/wp-content/uploads/2021/04/domestic-heat-pump.jpg',
  },
];
